definitions:
  template.TemplateModel:
    properties:
      id:
        type: string
      isDeleted:
        type: boolean
      name:
        type: string
      num:
        type: integer
    type: object
  user.UserModel:
    properties:
      id:
        type: string
      isDeleted:
        type: boolean
      name:
        type: string
      num:
        type: integer
    type: object
host: 127.0.0.1:8000
info:
  contact: {}
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Swagger Example API
  version: "1.0"
paths:
  /templates:
    get:
      consumes:
      - application/json
      parameters:
      - example: 1
        in: query
        minimum: 1
        name: page
        required: true
        type: integer
      - example: 10
        in: query
        minimum: 1
        name: pageSize
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/template.TemplateModel'
            type: array
        "400":
          description: Bad Request
          schema:
            type: object
      summary: getTemplateList
      tags:
      - template
    post:
      consumes:
      - application/json
      parameters:
      - description: template info object
        in: body
        name: template-info
        required: true
        schema:
          $ref: '#/definitions/template.TemplateModel'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/template.TemplateModel'
        "400":
          description: Bad Request
          schema:
            type: object
      summary: addTemplate
      tags:
      - template
  /templates/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: template ID
        in: path
        name: id
        required: true
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/template.TemplateModel'
        "400":
          description: Bad Request
          schema:
            type: object
      summary: updateTemplateById
      tags:
      - template
    get:
      consumes:
      - application/json
      parameters:
      - description: template ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/template.TemplateModel'
        "400":
          description: Bad Request
          schema:
            type: object
      summary: getTemplateById
      tags:
      - template
    put:
      consumes:
      - application/json
      parameters:
      - description: template ID
        in: path
        name: id
        required: true
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/template.TemplateModel'
        "400":
          description: Bad Request
          schema:
            type: object
      summary: updateTemplateById
      tags:
      - template
  /users:
    get:
      consumes:
      - application/json
      parameters:
      - example: 1
        in: query
        minimum: 1
        name: page
        required: true
        type: integer
      - example: 10
        in: query
        minimum: 1
        name: pageSize
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/user.UserModel'
            type: array
        "400":
          description: Bad Request
          schema:
            type: object
      summary: getUserList
      tags:
      - user
    post:
      consumes:
      - application/json
      parameters:
      - description: user info object
        in: body
        name: userinfo
        required: true
        schema:
          $ref: '#/definitions/user.UserModel'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.UserModel'
        "400":
          description: Bad Request
          schema:
            type: object
      summary: addUser
      tags:
      - user
  /users/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: user ID
        in: path
        name: id
        required: true
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.UserModel'
        "400":
          description: Bad Request
          schema:
            type: object
      summary: updateUserById
      tags:
      - user
    get:
      consumes:
      - application/json
      parameters:
      - description: user ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.UserModel'
        "400":
          description: Bad Request
          schema:
            type: object
      summary: getUserById
      tags:
      - user
    put:
      consumes:
      - application/json
      parameters:
      - description: user ID
        in: path
        name: id
        required: true
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.UserModel'
        "400":
          description: Bad Request
          schema:
            type: object
      summary: updateUserById
      tags:
      - user
swagger: "2.0"
