definitions:
  user.User:
    properties:
      name:
        example: zhangsan
        type: string
      pass:
        type: string
      phone:
        example: "13600000000"
        type: string
    required:
    - name
    - phone
    type: object
host: 127.0.0.1:8000
info:
  contact: {}
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Swagger Example API
  version: "1.0"
paths:
  /users:
    post:
      consumes:
      - application/json
      description: save user
      parameters:
      - description: user info object
        in: body
        name: userinfo
        required: true
        schema:
          $ref: '#/definitions/user.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.User'
        "400":
          description: Bad Request
          schema:
            type: object
      summary: addUser
      tags:
      - user
  /users/:id:
    get:
      consumes:
      - application/json
      description: get user info
      parameters:
      - description: user ID
        in: path
        name: id
        required: true
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.User'
        "400":
          description: Bad Request
          schema:
            type: object
      summary: getUserById
      tags:
      - user
swagger: "2.0"
